# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1He-km612ZSkTbOq9h1i_I2pBaZzjVkPL
"""

import pandas as pd

df = pd.read_csv("indian_houseprice_dataset.csv")

# Check missing values
print(df.isnull().sum())

# Remove duplicates
df.drop_duplicates(inplace=True)

# Fill missing values
df.fillna(df.median(numeric_only=True), inplace=True)

print(df.head())

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X = df.drop("Price", axis=1)
y = df["Price"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

import joblib

joblib.dump(model, "house_price_model.pkl")

from fastapi import FastAPI
import joblib
import pandas as pd

app = FastAPI()

model = joblib.load("house_price_model.pkl")

@app.get("/")
def home():
    return {
        "message": "House Price Prediction API"
    }

@app.post("/predict")
def predict(data: dict):

    df = pd.DataFrame([data])

    prediction = model.predict(df)

    return {
        "predicted_price": float(prediction[0])
    }