# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16OBkhS5VFlpS-_IW87E-GS4KzLRX5sLm
"""

#import  librarys
import pandas as pd
import numpy as np

#read the csv
df=pd.read_csv('indian_houseprice_dataset.csv')

#To get the information
df.info()

#to print head
df.head(5)

df.tail()

df.drop_duplicates(inplace=True)

print(df.columns)

# 6. Check Statistical Summary
df.describe()

# 7. Find Missing Values
df.isnull().sum()

# 10. Remove Rows with Missing Values
df.dropna(inplace=True)

# 12. Remove Duplicate Records
df.drop_duplicates(inplace=True)

